version: '3.8'

volumes:
  psql_data:

services:
  postgres:
    image: postgres:14
    ports:
      - 5432:5432
    volumes:
      - psql_data:/var/lib/postgresql/data
    labels:
      quarkus.forge.devservices: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres