name: Maven Build

on:
  push:
    branches:
      - '**'
    branches-ignore:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # The distribution of the JDK to be installed
          java-version: '21'     # The version of the JDK to be installed

      - name: Validate Maven Wrapper (Optional)
        run: ./mvnw --version

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: ./mvnw clean install

      - name: Test with Maven
        run: ./mvnw test